language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t owenthomasclark/d-k-complete -f Dockerfile.dev .

script:
    - docker run -e CI=true owenthomasclark/d-k-complete yarn test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-west-1-468064127171"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY