language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t owenthomasclark/d-k-complete -f Dockerfile.dev .

script:
    - docker run -e CI=true owenthomasclark/d-k-complete yarn test -- --coverage